# -*- coding: utf-8 -*-
"""Honey production with Linear regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o5ov4lKv1dFSv5EMEPcEtfEEx1rB9fDq

# Import the library
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model

"""# Read CSV Dataset
Import csv file in content folder
"""

df = pd.read_csv("/content/honeyproduction.csv")

df.head()

"""# Create X and y
From dataset, create two set of data to plot it.

"""

prod_per_year = df.groupby('year').totalprod.mean().reset_index()
X = prod_per_year["year"].values.reshape(-1, 1)
y = prod_per_year["totalprod"]

plt.scatter(X,y)
plt.show()

"""# Prediction with Linear Regression"""

regr = linear_model.LinearRegression()
regr.fit(X,y)

#print("regr.coef_: ", regr.coef_, " regr.intercept_: ", regr.intercept_)

y_predict = regr.predict(X)
plt.scatter(X,y)
plt.plot(X, y_predict)
plt.show()

"""# Prediction from 2013 to 2050"""

X_future = np.array(range(2013, 2051))
X_future = X_future.reshape(-1, 1)

future_predict = regr.predict(X_future)

plt.plot(X_future, future_predict)
plt.scatter(X,y)
plt.plot(X, y_predict)

plt.show()